import type { AssessmentDefinition } from '../types';
import { scenarioQuestion } from './builders';

export const animalPersonalityDefinition: AssessmentDefinition = {
  id: 'animal-personality-test',
  title: '动物人格测试',
  subtitle: '如果性格有一种动物气质，你更接近哪一种？',
  group: 'fun',
  questionCount: 18,
  estimatedMinutes: 4,
  mode: 'dominant',
  sensitive: false,
  intro: '从日常选择、社交方式和面对变化的反应中，拼出一张轻松有趣的动物人格画像。请选择最像你自然反应的答案。',
  disclaimer: '结果仅供自我探索和娱乐，不构成心理诊断或专业建议。',
  minAnsweredRatio: 1,
  dimensions: [
    { id: 'cat', label: '猫系', color: '#9a6b52', description: '独立观察与清晰边界' },
    { id: 'dog', label: '犬系', color: '#c97932', description: '真诚联结与稳定陪伴' },
    { id: 'fox', label: '狐系', color: '#b5542e', description: '灵活判断与策略解题' },
    { id: 'wolf', label: '狼系', color: '#566274', description: '坚定目标与责任担当' },
    { id: 'otter', label: '水獭系', color: '#3d8b87', description: '好奇活力与气氛感染' },
    { id: 'deer', label: '鹿系', color: '#7a9b68', description: '温和感知与细腻共情' },
  ],
  questions: [
    scenarioQuestion('animal-01', '临时空出一个下午，你最想怎么安排？', [
      ['找个舒服角落，安静做自己的事', 'cat', 'deer'],
      ['约熟悉的人见面，一起分享近况', 'dog', 'otter'],
      ['顺着兴趣探索一家没去过的小店', 'fox', 'cat'],
      ['完成一件拖了很久的重要事项', 'wolf', 'dog'],
    ]),
    scenarioQuestion('animal-02', '来到一个不太熟悉的聚会，你通常会？', [
      ['主动制造轻松话题，让场子热起来', 'otter', 'dog'],
      ['先照顾看起来有些拘谨的人', 'deer', 'cat'],
      ['观察一会儿，再选择想聊的人', 'cat', 'fox'],
      ['跟着认识的人行动，保持自然互动', 'dog', 'wolf'],
    ]),
    scenarioQuestion('animal-03', '朋友之间出现分歧时，你更可能？', [
      ['换个角度找出双方都没注意的解法', 'fox', 'cat'],
      ['明确问题和底线，推动事情解决', 'wolf', 'dog'],
      ['用一点幽默缓和紧张气氛', 'otter', 'deer'],
      ['先理解每个人真正介意的是什么', 'deer', 'otter'],
    ]),
    scenarioQuestion('animal-04', '进入一个全新的环境时，你会先？', [
      ['确认自己的空间和行动边界', 'cat', 'deer'],
      ['找到可以互相照应的伙伴', 'dog', 'otter'],
      ['快速摸清规则和隐藏机会', 'fox', 'cat'],
      ['确定目标，再建立稳定节奏', 'wolf', 'dog'],
    ]),
    scenarioQuestion('animal-05', '朋友情绪低落时，你最自然的做法是？', [
      ['陪他做点轻松的小事，找回一点活力', 'otter', 'dog'],
      ['安静听完，让对方感到被理解', 'deer', 'cat'],
      ['给对方空间，同时保持随时可联系', 'cat', 'fox'],
      ['持续陪伴，并记得后续再问候', 'dog', 'wolf'],
    ]),
    scenarioQuestion('animal-06', '团队合作中，你常承担哪种角色？', [
      ['发现捷径，处理棘手的临时问题', 'fox', 'cat'],
      ['守住目标，确保关键任务落地', 'wolf', 'dog'],
      ['连接大家，让合作更有参与感', 'otter', 'deer'],
      ['留意成员状态，减少无形摩擦', 'deer', 'otter'],
    ]),
    scenarioQuestion('animal-07', '面对还不确定的事情，你倾向于？', [
      ['先保留判断，继续独立观察', 'cat', 'deer'],
      ['和信任的人讨论，获得现实支持', 'dog', 'otter'],
      ['准备几套方案，随变化调整', 'fox', 'cat'],
      ['抓住可控部分，一步步推进', 'wolf', 'dog'],
    ]),
    scenarioQuestion('animal-08', '别人突然问起你的私事，你通常会？', [
      ['开个玩笑，自然地换个话题', 'otter', 'dog'],
      ['温和说明自己暂时不想谈', 'deer', 'cat'],
      ['只分享自己愿意公开的那一部分', 'cat', 'fox'],
      ['如果关系足够信任，会坦诚回答', 'dog', 'wolf'],
    ]),
    scenarioQuestion('animal-09', '遇到竞争时，你更像哪一种反应？', [
      ['研究规则，找到最聪明的突破口', 'fox', 'cat'],
      ['把注意力放在目标上，稳定输出', 'wolf', 'dog'],
      ['享受过程，用活力带动自己的状态', 'otter', 'deer'],
      ['不伤害关系，也认真争取应得结果', 'deer', 'otter'],
    ]),
    scenarioQuestion('animal-10', '旅行中最让你舒服的节奏是？', [
      ['保留独处时间，不把行程塞满', 'cat', 'deer'],
      ['和喜欢的人一起经历和分享', 'dog', 'otter'],
      ['根据现场线索随时调整路线', 'fox', 'cat'],
      ['提前确认重点，不错过核心计划', 'wolf', 'dog'],
    ]),
    scenarioQuestion('animal-11', '原计划突然改变，你会？', [
      ['把变化当成新游戏，先看看有什么乐趣', 'otter', 'dog'],
      ['确认大家是否都能适应新的安排', 'deer', 'cat'],
      ['先退一步观察，再决定是否参与', 'cat', 'fox'],
      ['积极配合，并帮忙稳定现场情绪', 'dog', 'wolf'],
    ]),
    scenarioQuestion('animal-12', '受到夸奖时，你更接近哪种反应？', [
      ['会想知道自己具体哪里做得好', 'fox', 'cat'],
      ['接受认可，也记得下一步目标', 'wolf', 'dog'],
      ['开心回应，让喜悦自然流动起来', 'otter', 'deer'],
      ['有点害羞，但会认真记住这份善意', 'deer', 'otter'],
    ]),
    scenarioQuestion('animal-13', '压力很大时，你最需要什么？', [
      ['一段不被打扰的安静时间', 'cat', 'deer'],
      ['可靠的人陪在身边或听我说说', 'dog', 'otter'],
      ['重新分析局面，找回选择空间', 'fox', 'cat'],
      ['把任务拆开，逐项完成恢复掌控', 'wolf', 'dog'],
    ]),
    scenarioQuestion('animal-14', '真正放松下来时，你喜欢？', [
      ['做点有趣又不太有目的的小事', 'otter', 'dog'],
      ['去自然或安静的地方慢慢恢复', 'deer', 'cat'],
      ['待在熟悉空间，按自己的节奏生活', 'cat', 'fox'],
      ['和亲近的人一起吃饭聊天', 'dog', 'wolf'],
    ]),
    scenarioQuestion('animal-15', '制定计划时，你通常更重视？', [
      ['保留可以调整和绕行的空间', 'fox', 'cat'],
      ['目标明确、责任清楚、能落地', 'wolf', 'dog'],
      ['过程有趣，大家愿意参与', 'otter', 'deer'],
      ['节奏舒适，不让任何人被忽略', 'deer', 'otter'],
    ]),
    scenarioQuestion('animal-16', '遇到一个新鲜事物，你更可能？', [
      ['先远远观察，确认自己是否感兴趣', 'cat', 'deer'],
      ['邀请朋友一起尝试，互相照应', 'dog', 'otter'],
      ['立刻研究它还能怎么玩出新花样', 'fox', 'cat'],
      ['判断是否值得投入，再认真行动', 'wolf', 'dog'],
    ]),
    scenarioQuestion('animal-17', '在亲密关系里，你最看重？', [
      ['能一起笑、一起发现生活里的惊喜', 'otter', 'dog'],
      ['被温柔理解，也能照顾彼此感受', 'deer', 'cat'],
      ['亲近但不过度干涉，尊重各自空间', 'cat', 'fox'],
      ['稳定回应、彼此信任和长期陪伴', 'dog', 'wolf'],
    ]),
    scenarioQuestion('animal-18', '做重要决定时，你更依赖？', [
      ['快速识别局势中的关键变量', 'fox', 'cat'],
      ['长期目标和自己愿意承担的责任', 'wolf', 'dog'],
      ['内心的兴奋感和行动活力', 'otter', 'deer'],
      ['决定是否符合自己的感受与善意', 'deer', 'otter'],
    ]),
  ],
  results: [
    { id: 'cat', title: '猫系观察家', description: '你习惯先观察再靠近，珍惜独处、自由和清晰边界。你不一定热衷成为焦点，却常能察觉环境里细微的变化。', keywords: ['独立', '敏锐', '边界感'], suggestion: '保留自己的节奏，也可以更直接地告诉重要的人你需要怎样的陪伴。' },
    { id: 'dog', title: '犬系同行者', description: '你重视真诚回应和可靠陪伴，愿意把热情投入熟悉的人与共同目标。别人常能从你身上感到稳定和被支持。', keywords: ['真诚', '热情', '可靠'], suggestion: '照顾别人时也记得检查自己的能量，不必把所有责任都揽在身上。' },
    { id: 'fox', title: '狐系解题者', description: '你擅长观察规则、切换角度并寻找灵活路径。面对复杂局面时，你往往能比别人更早看到选择与突破口。', keywords: ['灵活', '机敏', '策略感'], suggestion: '聪明的方案若能配上清晰表达，会更容易获得同伴信任。' },
    { id: 'wolf', title: '狼系守望者', description: '你对目标、承诺和责任有稳定感，关键时刻愿意站出来承担。你可能不轻易表态，但一旦认定就会持续投入。', keywords: ['坚定', '责任', '目标感'], suggestion: '坚定之外也允许计划有弹性，适时求助不会削弱你的可靠。' },
    { id: 'otter', title: '水獭系气氛家', description: '你好奇、有活力，容易被新鲜体验和人与人之间的火花点亮。你擅长把轻松感带进群体，让生活重新流动。', keywords: ['好奇', '活力', '感染力'], suggestion: '在追逐新鲜感时，为真正重要的事情保留一点持续投入。' },
    { id: 'deer', title: '鹿系共情者', description: '你对情绪和关系氛围十分敏感，愿意用温和方式理解和照顾他人。你的力量不喧哗，却能让人感到安全。', keywords: ['温和', '细腻', '同理心'], suggestion: '同理不等于委屈自己，明确边界能让温柔更长久。' },
  ],
  tieBreakOrder: ['cat', 'dog', 'fox', 'wolf', 'otter', 'deer'],
};
