import type { AssessmentDefinition } from '../types';
import { scenarioQuestion } from './builders';

export const coreValuesDefinition: AssessmentDefinition = {
  id: 'core-values-test',
  title: '核心价值观测试',
  subtitle: '自由、稳定、成就、联结、探索与贡献，什么最能驱动你？',
  group: 'personality', questionCount: 18, estimatedMinutes: 5, mode: 'dominant', sensitive: false,
  intro: '价值观不是道德排名，而是你在取舍时更想守住的东西。面对每个情境，请选择最接近你真实优先级的答案。',
  disclaimer: '结果仅供自我探索，不构成职业、关系或人生决策建议。',
  minAnsweredRatio: 1,
  dimensions: [
    { id: 'autonomy', label: '自主', color: '#9a5a45', description: '选择权、独立性与按自己方式生活' },
    { id: 'stability', label: '稳定', color: '#657f63', description: '安全感、可预期与长期可持续' },
    { id: 'achievement', label: '成就', color: '#b17b2d', description: '成长、影响力与完成重要目标' },
    { id: 'connection', label: '联结', color: '#a15f78', description: '归属、亲密与彼此支持' },
    { id: 'exploration', label: '探索', color: '#547d91', description: '好奇、新体验与认知扩展' },
    { id: 'contribution', label: '贡献', color: '#7a6690', description: '助人、公共价值与留下积极影响' },
  ],
  questions: [
    scenarioQuestion('values-01', '选择一份工作时，你最不愿放弃的是？', [
      ['有自主决定方法和节奏的空间', 'autonomy', 'exploration'],
      ['稳定收入和可预期的发展路径', 'stability', 'connection'],
      ['能持续成长并取得看得见的成果', 'achievement', 'autonomy'],
      ['团队互相信任，关系有归属感', 'connection', 'contribution'],
    ]),
    scenarioQuestion('values-02', '如果考虑搬到新城市，最吸引你的理由是？', [
      ['能接触不同生活方式和未知体验', 'exploration', 'autonomy'],
      ['能做对他人或社区有意义的事情', 'contribution', 'connection'],
      ['可以重新定义自己的生活，不受旧期待限制', 'autonomy', 'exploration'],
      ['基础条件可靠，生活风险更可控', 'stability', 'connection'],
    ]),
    scenarioQuestion('values-03', '拥有一段完全自由的时间，你更想？', [
      ['完成一个一直想实现的目标', 'achievement', 'autonomy'],
      ['与重要的人认真相处和分享', 'connection', 'contribution'],
      ['学习陌生领域或去没去过的地方', 'exploration', 'autonomy'],
      ['参与一件能帮助别人的事情', 'contribution', 'connection'],
    ]),
    scenarioQuestion('values-04', '面对艰难决定，你最看重？', [
      ['选择是否真正出自我的意愿', 'autonomy', 'exploration'],
      ['选择是否能保住长期安全与秩序', 'stability', 'connection'],
      ['选择是否让我继续成长和前进', 'achievement', 'autonomy'],
      ['选择是否照顾了重要关系', 'connection', 'contribution'],
    ]),
    scenarioQuestion('values-05', '哪种生活更容易让你兴奋？', [
      ['持续出现新问题、新知识和新体验', 'exploration', 'autonomy'],
      ['能把时间投入值得帮助的人与议题', 'contribution', 'connection'],
      ['可以自由安排，不被过多规则束缚', 'autonomy', 'exploration'],
      ['节奏稳定，重要资源都有保障', 'stability', 'connection'],
    ]),
    scenarioQuestion('values-06', '你怎样理解“成功”？', [
      ['把能力发挥到更高水平，做成重要的事', 'achievement', 'autonomy'],
      ['拥有相互支持、可以信任的关系', 'connection', 'contribution'],
      ['始终保持好奇，不断扩展世界', 'exploration', 'autonomy'],
      ['让自己的努力对别人产生积极影响', 'contribution', 'connection'],
    ]),
    scenarioQuestion('values-07', '金钱对你最重要的意义是？', [
      ['让我拥有说“不”和选择生活的自由', 'autonomy', 'exploration'],
      ['提供安全垫，让未来不至于失控', 'stability', 'connection'],
      ['证明努力有成果，并支持更大目标', 'achievement', 'autonomy'],
      ['能照顾家人，与重要的人共享生活', 'connection', 'contribution'],
    ]),
    scenarioQuestion('values-08', '当未来不确定时，什么最能给你方向？', [
      ['继续尝试，在行动中发现新路径', 'exploration', 'autonomy'],
      ['确认自己仍能为他人创造一点价值', 'contribution', 'connection'],
      ['保留决定权，不让别人替我定义答案', 'autonomy', 'exploration'],
      ['建立可靠日常，先守住生活底盘', 'stability', 'connection'],
    ]),
    scenarioQuestion('values-09', '友谊中你最珍惜的是？', [
      ['彼此鼓励成长，一起完成有挑战的事', 'achievement', 'autonomy'],
      ['被理解、被接纳，也愿意互相陪伴', 'connection', 'contribution'],
      ['能分享不同观点，一起发现新世界', 'exploration', 'autonomy'],
      ['在对方需要时真正提供帮助', 'contribution', 'connection'],
    ]),
    scenarioQuestion('values-10', '学习一项技能时，最让你满足的是？', [
      ['可以形成自己的方法和表达', 'autonomy', 'exploration'],
      ['按稳定节奏积累，越来越扎实', 'stability', 'connection'],
      ['达到更高标准，突破原有水平', 'achievement', 'autonomy'],
      ['能与别人交流、合作或共同练习', 'connection', 'contribution'],
    ]),
    scenarioQuestion('values-11', '获得认可时，哪种认可最打动你？', [
      ['别人欣赏我的好奇和独特视角', 'exploration', 'autonomy'],
      ['别人说我的行动确实帮助了他们', 'contribution', 'connection'],
      ['别人尊重我的选择和独立判断', 'autonomy', 'exploration'],
      ['别人信任我的可靠和长期投入', 'stability', 'connection'],
    ]),
    scenarioQuestion('values-12', '面对日常规律，你更希望它？', [
      ['服务目标，让自己持续变得更强', 'achievement', 'autonomy'],
      ['为重要关系留出稳定时间', 'connection', 'contribution'],
      ['不断加入新鲜内容，不陷入停滞', 'exploration', 'autonomy'],
      ['包含一些对他人和环境有益的行动', 'contribution', 'connection'],
    ]),
    scenarioQuestion('values-13', '如果要承担一次风险，你更愿意因为？', [
      ['这能让我忠于自己的选择', 'autonomy', 'exploration'],
      ['它能换来更可靠的长期生活', 'stability', 'connection'],
      ['它值得我挑战更高目标', 'achievement', 'autonomy'],
      ['它能守护一段重要关系', 'connection', 'contribution'],
    ]),
    scenarioQuestion('values-14', '参与一个社区时，你最期待？', [
      ['接触不同的人和从未想过的观点', 'exploration', 'autonomy'],
      ['一起改善真实问题，产生公共价值', 'contribution', 'connection'],
      ['保持个人空间，不被集体过度要求', 'autonomy', 'exploration'],
      ['规则可靠，成员之间长期稳定', 'stability', 'connection'],
    ]),
    scenarioQuestion('values-15', '成为负责人时，你最在意？', [
      ['带领团队完成有分量的成果', 'achievement', 'autonomy'],
      ['让成员有归属感并彼此支持', 'connection', 'contribution'],
      ['鼓励试验，让新想法真正发生', 'exploration', 'autonomy'],
      ['让决策对更多人带来正向影响', 'contribution', 'connection'],
    ]),
    scenarioQuestion('values-16', '经历挫折后，什么最能让你重新站起来？', [
      ['我仍可以选择接下来如何回应', 'autonomy', 'exploration'],
      ['生活中还有可靠的人和固定支点', 'stability', 'connection'],
      ['我仍想证明自己可以做得更好', 'achievement', 'autonomy'],
      ['有人愿意理解我、陪我一起走', 'connection', 'contribution'],
    ]),
    scenarioQuestion('values-17', '规划未来五年时，你会优先想到？', [
      ['还想看见哪些地方、学习哪些领域', 'exploration', 'autonomy'],
      ['希望为哪些人或事情留下价值', 'contribution', 'connection'],
      ['怎样让生活更符合自己的定义', 'autonomy', 'exploration'],
      ['怎样建立更稳固的生活基础', 'stability', 'connection'],
    ]),
    scenarioQuestion('values-18', '哪种一天结束时最让你感到充实？', [
      ['完成了有难度、能看见进步的任务', 'achievement', 'autonomy'],
      ['与重要的人有真实而温暖的连接', 'connection', 'contribution'],
      ['发现了一个新问题或新世界', 'exploration', 'autonomy'],
      ['让某个人或某件事因为我变好一点', 'contribution', 'connection'],
    ]),
  ],
  results: [
    { id: 'autonomy', title: '自主驱动', description: '你很看重选择权、独立判断和按自己方式生活。只有当决定真正出自内心，你才容易长期投入。', keywords: ['自由', '独立', '选择权'], suggestion: '自主与连接可以共存，提前说明边界会减少不必要的对抗。' },
    { id: 'stability', title: '稳定驱动', description: '安全感、规律和可持续是你的重要底盘。你愿意通过长期建设，让生活不被短期波动轻易打乱。', keywords: ['安全感', '规律', '可持续'], suggestion: '在可靠底盘上安排小范围试验，稳定也能容纳成长。' },
    { id: 'achievement', title: '成就驱动', description: '成长、标准和完成有分量的目标能强烈驱动你。你喜欢看到能力被验证，也愿意为进步投入努力。', keywords: ['成长', '目标', '影响力'], suggestion: '把休息纳入长期目标，避免只用成果衡量自己的价值。' },
    { id: 'connection', title: '联结驱动', description: '归属、理解和相互支持是你做决定时的重要坐标。与重要的人共享生活，会让许多努力变得值得。', keywords: ['归属', '亲密', '支持'], suggestion: '关系重要，但你的个人需要也值得被清楚表达。' },
    { id: 'exploration', title: '探索驱动', description: '好奇、新体验和认知扩展让你感到生命在流动。你愿意走出熟悉边界，不断更新对世界的理解。', keywords: ['好奇', '新体验', '开放'], suggestion: '选择一个最重要的探索持续深入，会让广度转化为真正积累。' },
    { id: 'contribution', title: '贡献驱动', description: '你希望时间和能力能对他人、社区或更大的议题产生积极影响。意义感常比单纯回报更能支持你坚持。', keywords: ['助人', '意义', '公共价值'], suggestion: '贡献也需要边界，先保护自己的资源才能长期帮助别人。' },
  ],
  tieBreakOrder: ['autonomy', 'stability', 'achievement', 'connection', 'exploration', 'contribution'],
};
