import React, { useState } from 'react';
import { Btn } from '../../shared';
import { addPdfPageNumbers, clearPdfMetadata, cropPdfPages, readPdfMetadata, reorderPdfPages, resizePdfPages } from './core';
import { extractPdfLinks, renderPdfToLongImage } from './render';
import { PdfToolShell, type PdfToolResult } from './PdfToolShell';
import { convertDocument } from '../../document/documentConversionApi';

type ToolProps = { onClose: () => void };
const inputClass = 'rounded-lg border border-[#d8b58e] bg-[#fff4e6] px-3 py-2 text-sm text-[#2f241b] focus:border-[#9a5a28] focus:outline-none';
const pdfBlob = (bytes: Uint8Array) => new Blob([bytes as unknown as BlobPart], { type: 'application/pdf' });
const Field: React.FC<{ label: string; value: string; onChange: (value: string) => void; type?: string }> = ({ label, value, onChange, type = 'text' }) => <label className="text-xs font-medium text-[#6d5a47]">{label}<input type={type} className={`mt-1 block w-28 ${inputClass}`} value={value} onChange={(event) => onChange(event.target.value)} /></label>;

export const PdfPageNumbersTool: React.FC<ToolProps> = ({ onClose }) => { const [start, setStart] = useState('1'); const [position, setPosition] = useState('bottom-center'); const [fontSize, setFontSize] = useState('12'); const [marginMm, setMarginMm] = useState('10'); return <PdfToolShell onClose={onClose} title="PDF 页码添加" description="为全部页面或指定页面添加清晰的页码，输出仍是 PDF。" onProcess={async (file) => ({ blob: pdfBlob(await addPdfPageNumbers(new Uint8Array(await file.arrayBuffer()), { start: Number(start), position: position as any, fontSize: Number(fontSize), marginMm: Number(marginMm) })), filename: `${file.name.replace(/\.pdf$/i, '')}-numbered.pdf` })}><div className="flex flex-wrap gap-3"><Field label="起始页码" value={start} onChange={setStart} type="number" /><Field label="字号" value={fontSize} onChange={setFontSize} type="number" /><Field label="边距（mm）" value={marginMm} onChange={setMarginMm} type="number" /><label className="text-xs font-medium text-[#6d5a47]">位置<select className={`mt-1 block ${inputClass}`} value={position} onChange={(event) => setPosition(event.target.value)}><option value="top-left">顶部左</option><option value="top-center">顶部中</option><option value="top-right">顶部右</option><option value="bottom-left">底部左</option><option value="bottom-center">底部中</option><option value="bottom-right">底部右</option></select></label></div></PdfToolShell>; };

export const PdfCropTool: React.FC<ToolProps> = ({ onClose }) => { const [top, setTop] = useState('5'); const [right, setRight] = useState('5'); const [bottom, setBottom] = useState('5'); const [left, setLeft] = useState('5'); return <PdfToolShell onClose={onClose} title="PDF 页面裁剪" description="统一裁剪每页四边空白区域，边距以毫米输入。" onProcess={async (file) => ({ blob: pdfBlob(await cropPdfPages(new Uint8Array(await file.arrayBuffer()), { top: Number(top), right: Number(right), bottom: Number(bottom), left: Number(left) })), filename: `${file.name.replace(/\.pdf$/i, '')}-cropped.pdf` })}><div className="flex flex-wrap gap-3"><Field label="上（mm）" value={top} onChange={setTop} type="number" /><Field label="右（mm）" value={right} onChange={setRight} type="number" /><Field label="下（mm）" value={bottom} onChange={setBottom} type="number" /><Field label="左（mm）" value={left} onChange={setLeft} type="number" /></div></PdfToolShell>; };

export const PdfPageSizeTool: React.FC<ToolProps> = ({ onClose }) => { const [preset, setPreset] = useState('A4'); const [orientation, setOrientation] = useState('portrait'); return <PdfToolShell onClose={onClose} title="PDF 页面尺寸" description="将 PDF 页面统一调整为 A4、A3、Letter 或 Legal，并居中保留内容。" onProcess={async (file) => ({ blob: pdfBlob(await resizePdfPages(new Uint8Array(await file.arrayBuffer()), { preset: preset as any, orientation: orientation as any })), filename: `${file.name.replace(/\.pdf$/i, '')}-${preset}.pdf` })}><div className="flex flex-wrap gap-3"><label className="text-xs font-medium text-[#6d5a47]">目标尺寸<select className={`mt-1 block ${inputClass}`} value={preset} onChange={(event) => setPreset(event.target.value)}><option>A4</option><option>A3</option><option>Letter</option><option>Legal</option></select></label><label className="text-xs font-medium text-[#6d5a47]">方向<select className={`mt-1 block ${inputClass}`} value={orientation} onChange={(event) => setOrientation(event.target.value)}><option value="portrait">纵向</option><option value="landscape">横向</option></select></label></div></PdfToolShell>; };

export const PdfReorderTool: React.FC<ToolProps> = ({ onClose }) => { const [order, setOrder] = useState(''); return <PdfToolShell onClose={onClose} title="PDF 页面重排" description="用页码顺序重新排列页面，例如 3,1,2；每页必须出现且不能重复。" onProcess={async (file) => { const bytes = new Uint8Array(await file.arrayBuffer()); const { PDFDocument } = await import('pdf-lib'); const source = await PDFDocument.load(bytes, { updateMetadata: false }); const count = source.getPageCount(); const indexes = (order.trim() ? order.split(/[,，\s]+/).map((value) => Number(value) - 1) : Array.from({ length: count }, (_, index) => index)); const output = await reorderPdfPages(bytes, indexes); return { blob: pdfBlob(output), filename: `${file.name.replace(/\.pdf$/i, '')}-reordered.pdf` }; }}><Field label="新顺序（1-based）" value={order} onChange={setOrder} /></PdfToolShell>; };

export const PdfLongImageTool: React.FC<ToolProps> = ({ onClose }) => { const [dpi, setDpi] = useState('144'); return <PdfToolShell onClose={onClose} title="PDF 长图导出" description="按页面顺序拼接为一张 PNG 长图，自动限制宽度并保护浏览器内存。" onProcess={async (file) => ({ blob: await renderPdfToLongImage(new Uint8Array(await file.arrayBuffer()), { dpi: Number(dpi) }), filename: `${file.name.replace(/\.pdf$/i, '')}-long.png` })}><Field label="清晰度 DPI" value={dpi} onChange={setDpi} type="number" /></PdfToolShell>; };

export const PdfMetadataTool: React.FC<ToolProps> = ({ onClose }) => { const [metadata, setMetadata] = useState<Awaited<ReturnType<typeof readPdfMetadata>> | null>(null); const [clear, setClear] = useState(true); const handleFile = async (file: File) => { try { setMetadata(await readPdfMetadata(new Uint8Array(await file.arrayBuffer()))); } catch { setMetadata(null); } }; return <PdfToolShell onClose={onClose} title="PDF 元数据清理" description="读取标题、作者、关键词和日期，并生成清理后的副本。" onFileChange={handleFile} onProcess={async (file) => ({ blob: pdfBlob(await clearPdfMetadata(new Uint8Array(await file.arrayBuffer()), { clearDates: clear })), filename: `${file.name.replace(/\.pdf$/i, '')}-metadata-clean.pdf` })}><div className="space-y-2"><label className="flex items-center gap-2 text-sm text-[#6d5a47]"><input type="checkbox" checked={clear} onChange={(event) => setClear(event.target.checked)} />同时清除创建/修改日期</label>{metadata && <dl className="grid gap-1 text-xs text-[#6d5a47] sm:grid-cols-2"><div><dt className="inline font-semibold">标题：</dt><dd className="inline">{metadata.title || '（空）'}</dd></div><div><dt className="inline font-semibold">作者：</dt><dd className="inline">{metadata.author || '（空）'}</dd></div><div><dt className="inline font-semibold">关键词：</dt><dd className="inline">{metadata.keywords.join('、') || '（空）'}</dd></div><div><dt className="inline font-semibold">创建日期：</dt><dd className="inline">{metadata.creationDate || '（空）'}</dd></div></dl>}</div></PdfToolShell>; };

export const PdfLinkExtractorTool: React.FC<ToolProps> = ({ onClose }) => <PdfToolShell onClose={onClose} title="PDF 链接提取" description="提取 PDF 中的安全 HTTP(S) 链接，过滤脚本和本地文件地址。" onProcess={async (file) => { const links = await extractPdfLinks(new Uint8Array(await file.arrayBuffer())); const text = JSON.stringify(links, null, 2); return { text, blob: new Blob([text], { type: 'application/json;charset=utf-8' }), filename: `${file.name.replace(/\.pdf$/i, '')}-links.json` }; }} />;

export const PdfToWordTool: React.FC<ToolProps> = ({ onClose }) => <PdfToolShell onClose={onClose} privacy="backend-upload" title="PDF → Word（图片版）" description="调用本站文档转换服务，把每页 PDF 渲染为图片写入 DOCX；版式稳定但文字不可编辑。" onProcess={async (file): Promise<PdfToolResult> => { const result = await convertDocument([file], 'pdf-to-word-image'); return { blob: result.blob, filename: result.filename }; }} />;
