import React, { useState } from 'react';
import { Btn } from '../shared';
import { buildMetaTags, buildRobotsTxt, buildSitemapXml, buildUtmUrl, parseUrl, parseUserAgent, slugify } from './core';
import { inspectDns, inspectHttp, inspectSsl, inspectWebSocket } from './api';
import { WebmasterWorkbench } from './WebmasterWorkbench';

type ToolProps = { onClose: () => void };
const inputClass = 'rounded-lg border border-[#d8b58e] bg-[#fff4e6] px-3 py-2 text-sm text-[#2f241b] focus:border-[#9a5a28] focus:outline-none';
const Field: React.FC<{ label: string; value: string; onChange: (value: string) => void; placeholder?: string }> = ({ label, value, onChange, placeholder }) => <label className="text-xs font-medium text-[#6d5a47]">{label}<input className={`mt-1 block min-w-[180px] ${inputClass}`} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} /></label>;

export const MetaTagTool: React.FC<ToolProps> = ({ onClose }) => { const [title, setTitle] = useState('我的网站'); const [description, setDescription] = useState('网站描述'); const [url, setUrl] = useState('https://example.com/'); const [image, setImage] = useState(''); return <WebmasterWorkbench onClose={onClose} title="Meta 标签生成器" description="生成标题、描述、Canonical、Open Graph 和 Twitter Card 标签。" process={() => buildMetaTags({ title, description, url, image: image || undefined })} controls={<><Field label="标题" value={title} onChange={setTitle} /><Field label="描述" value={description} onChange={setDescription} /><Field label="Canonical URL" value={url} onChange={setUrl} /><Field label="分享图片 URL（可选）" value={image} onChange={setImage} /></>} />; };

export const OpenGraphPreviewTool: React.FC<ToolProps> = ({ onClose }) => { const [title, setTitle] = useState('分享标题'); const [description, setDescription] = useState('这里是分享摘要'); const [url, setUrl] = useState('https://example.com/'); const [generated, setGenerated] = useState(false); return <div className="space-y-5"><div><h2 className="text-lg font-semibold text-[#5f3214]">Open Graph 分享预览</h2><p className="mt-1 text-sm leading-6 text-[#6d5a47]">用真实文本和属性预览链接在社交平台中的展示效果。</p><p className="mt-1 text-xs text-[#5f6f42]">本地处理：输入不会上传。</p></div><div className="flex flex-wrap gap-3 rounded-lg border border-[#ead0ad] bg-[#fff8ef] p-3"><Field label="标题" value={title} onChange={setTitle} /><Field label="描述" value={description} onChange={setDescription} /><Field label="URL" value={url} onChange={setUrl} /></div><Btn onClick={() => setGenerated(true)}>生成预览</Btn>{generated && <div className="max-w-xl overflow-hidden rounded-xl border border-[#d8b58e] bg-white" data-testid="og-preview"><div className="h-24 bg-gradient-to-r from-indigo-600 to-sky-500" /><div className="p-4"><p className="text-xs text-[#8b735c]">{url}</p><h3 className="mt-1 font-semibold text-[#2f241b]">{title}</h3><p className="mt-1 text-sm text-[#6d5a47]">{description}</p></div></div>}<Btn onClick={onClose} variant="ghost">关闭</Btn></div>; };

export const RobotsTxtTool: React.FC<ToolProps> = ({ onClose }) => { const [sitemap, setSitemap] = useState('https://example.com/sitemap.xml'); const [disallow, setDisallow] = useState('/private\n/admin'); return <WebmasterWorkbench onClose={onClose} title="robots.txt 生成器" description="按规则生成可直接部署的 robots.txt，并检查换行注入。" process={() => buildRobotsTxt({ sitemap, disallow: disallow.split(/\r?\n/).filter(Boolean) })} controls={<><Field label="Sitemap URL" value={sitemap} onChange={setSitemap} /><Field label="Disallow（每行一条）" value={disallow} onChange={setDisallow} /></>} />; };

export const SitemapGeneratorTool: React.FC<ToolProps> = ({ onClose }) => { const [base, setBase] = useState('https://example.com'); return <WebmasterWorkbench onClose={onClose} title="Sitemap 生成器" description="根据 URL 列表生成符合协议的 XML sitemap。" process={(value) => buildSitemapXml(value.split(/\r?\n/).filter(Boolean).map((url) => ({ url, changefreq: 'weekly', priority: 0.8 })))} controls={<Field label="示例站点（可复制到输入框）" value={base} onChange={setBase} />} initialInput={`${base}/\n${base}/about`} inputLabel="URL 列表（每行一条）" />; };

export const UrlParserTool: React.FC<ToolProps> = ({ onClose }) => <WebmasterWorkbench onClose={onClose} title="URL 解析器" description="拆解协议、域名、端口、路径、哈希和重复查询参数。" process={(value) => JSON.stringify(parseUrl(value), null, 2)} initialInput="https://example.com:8443/path?tag=a&tag=b#part" actionLabel="解析" />;

export const UtmBuilderTool: React.FC<ToolProps> = ({ onClose }) => { const [source, setSource] = useState('wechat'); const [medium, setMedium] = useState('social'); const [campaign, setCampaign] = useState('summer'); const [term, setTerm] = useState(''); const [content, setContent] = useState(''); return <WebmasterWorkbench onClose={onClose} title="UTM 链接生成器" description="保留已有查询参数并追加来源、媒介和活动参数。" process={(value) => buildUtmUrl(value, { source, medium, campaign, term, content })} initialInput="https://example.com/?ref=home" controls={<><Field label="utm_source" value={source} onChange={setSource} /><Field label="utm_medium" value={medium} onChange={setMedium} /><Field label="utm_campaign" value={campaign} onChange={setCampaign} /><Field label="utm_term（可选）" value={term} onChange={setTerm} /><Field label="utm_content（可选）" value={content} onChange={setContent} /></>} />; };

export const SlugGeneratorTool: React.FC<ToolProps> = ({ onClose }) => <WebmasterWorkbench onClose={onClose} title="Slug 生成器" description="将标题转换为适合 URL 的 Unicode slug，保留中文并清理标点。" process={slugify} initialInput="你好，World 2026" />;
export const UserAgentParserTool: React.FC<ToolProps> = ({ onClose }) => <WebmasterWorkbench onClose={onClose} title="User-Agent 解析器" description="识别常见浏览器、操作系统和设备类型。" process={(value) => JSON.stringify(parseUserAgent(value), null, 2)} initialInput="Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1" actionLabel="解析" />;

const NetworkTool: React.FC<ToolProps & { title: string; description: string; label: string; inspect: (value: string) => Promise<unknown>; initial: string }> = ({ onClose, title, description, label, inspect, initial }) => <WebmasterWorkbench onClose={onClose} title={title} description={description} process={async (value) => JSON.stringify(await inspect(value), null, 2)} initialInput={initial} inputLabel={label} outputLabel="检测结果" local={false} actionLabel="开始检测" />;
export const SslCheckerTool: React.FC<ToolProps> = (props) => <NetworkTool {...props} title="SSL 证书检查" description="检查公开域名的 TLS 协议、证书主体、有效期和 SAN 数量。" label="域名" initial="example.com" inspect={inspectSsl} />;
export const DnsLookupTool: React.FC<ToolProps> = (props) => <NetworkTool {...props} title="DNS 查询" description="查询公开域名的 A/AAAA 地址，仅展示公共地址。" label="域名" initial="example.com" inspect={inspectDns} />;
export const HttpStatusTool: React.FC<ToolProps> = (props) => <NetworkTool {...props} title="HTTP 状态检查" description="使用受控 HEAD/零字节 GET 请求查看状态、响应头和重定向链。" label="HTTP(S) URL" initial="https://example.com/" inspect={inspectHttp} />;
export const WebSocketTesterTool: React.FC<ToolProps> = (props) => <NetworkTool {...props} title="WebSocket 握手测试" description="只执行标准初始握手，不发送应用数据。" label="WS(S) URL" initial="wss://echo.websocket.events/" inspect={inspectWebSocket} />;
