"""OpenWrite agent 工具分组。"""

from __future__ import annotations

ORCHESTRATOR_TOOLKIT = {
    "get_status",
    "get_context",
    "search_project",
    "query_library",
    "read_project_document",
    "edit_project_document",
    "list_chapters",
    "get_truth_files",
    "get_character_state",
    "create_character",
    "query_world",
    "get_world_relations",
    "review_chapter",
    "get_workflow_status",
    "start_workflow",
    "advance_workflow",
}

WRITING_TOOLKIT = {
    "write_chapter",
    "get_context",
    "list_chapters",
    "get_truth_files",
    "get_character_state",
}

DANTE_DIRECT_TOOLKIT = {
    "get_status",
    "get_context",
    "search_project",
    "query_library",
    "read_project_document",
    "edit_project_document",
    "list_chapters",
    "get_truth_files",
    "get_character_state",
    "create_character",
    "query_world",
    "get_world_relations",
    "search_relation_targets",
    "edit_world_relation",
    "edit_world_relations",
    "get_outline_structure",
    "edit_outline_structure",
    "inspect_agent_context",
    "list_chapter_runs",
    "get_chapter_run_v2",
    "record_chapter_intervention",
    "update_chapter_intervention",
    "cancel_chapter_run_v2",
    "diagnose_runtime",
    "manage_rolling_plan",
    "manage_manuscript_versions",
    "manage_annotations",
    "get_runtime_state",
    "get_chapter_review",
    "get_task_activity",
    "get_goethe_handoff",
}

DANTE_ACTION_TOOLKIT = {
    "summarize_ideation",
    "confirm_ideation_summary",
    "generate_outline_draft",
    "confirm_outline_scope",
    "run_chapter_preflight",
    "delegate_chapter_write",
    "delegate_chapter_review",
}

GOETHE_DIRECT_TOOLKIT = {
    "get_status",
    "get_context",
    "search_project",
    "query_library",
    "read_project_document",
    "edit_project_document",
    "list_chapters",
    "get_truth_files",
    "get_character_state",
    "create_character",
    "query_world",
    "get_world_relations",
    "search_relation_targets",
    "edit_world_relation",
    "edit_world_relations",
    "get_outline_structure",
    "edit_outline_structure",
    "inspect_agent_context",
    "list_chapter_runs",
    "get_chapter_run_v2",
    "record_chapter_intervention",
    "update_chapter_intervention",
    "cancel_chapter_run_v2",
    "diagnose_runtime",
    "manage_rolling_plan",
    "manage_narrative_forecast",
    "manage_manuscript_versions",
    "manage_annotations",
    "get_runtime_state",
    "get_chapter_review",
    "get_task_activity",
    "get_goethe_handoff",
}

GOETHE_ACTION_TOOLKIT = {
    "summarize_ideation",
    "confirm_ideation_summary",
    "generate_foundation_draft",
    "confirm_foundation",
    "generate_character_draft",
    "confirm_character_draft",
    "generate_outline_draft",
    "read_outline",
    "stage_outline_edits",
    "confirm_outline_edits",
    "discard_outline_edits",
    "extract_style_source",
    "extract_setting_source",
    "review_source_pack",
    "promote_source_pack",
    "list_reference_library",
    "review_reference_source",
    "review_reference_profile",
    "preview_reference_adoption",
    "apply_reference_adoption",
    "prepare_dante_handoff",
}
